### ISSUE TITLE
Create data-repo with test data

### ISSUE THREAD

**Issue by kmuehlbauer** [meteo-ubonn/miubrt#2]
It would be good to test the notebooks with some original data.

We could create a data-repo containing 1 hour of BoXPol volume data. @prabshr Any recommendation fpr that one hour (day + time)?

**Comment by prabshr** [comment]
Yes, it is definitely becoming a necessity in the processing phase too...
2015 default test case from 1400 to 1500 would be good !

**Comment by kmuehlbauer** [comment]
repo added https://github.com/meteo-ubonn/miubrt-test-data
