### ISSUE TITLE
Create CI workflow

### ISSUE THREAD

**Issue by kmuehlbauer** [meteo-ubonn/miubrt#4]
Now that we have the test data available (https://github.com/meteo-ubonn/miubrt-test-data) we can move forward and create an automated CI testing workflow. I would propose the following:

- [x] move code into submodules (first into io/util)
- [x] adapt notebook to be run within CI
- [x] adapt notebook to be run with installed version of `miubrt`
- [x] adapt notebook to be run with development version of `miubrt`
- [x] use GitHub Actions as CI service

**Comment by kmuehlbauer** [comment]
@prabshr Please add to this list, if something is missing.

**Comment by prabshr** [comment]
Looks fine to me !

**Comment by kmuehlbauer** [comment]
see #5
